version: '3.9'

networks:
  bridge:
    driver: bridge

services:
  nginx:
    image: nginx:1.22
    networks:
      - bridge
    links:
      - php
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    environment:
      - TZ=Europe/Moscow
    depends_on:
      - php

  php:
    image: yiisoftware/yii2-php:8.1-fpm
    networks:
      - bridge
    links:
      - mysql
    volumes:
      - ./src:/var/www/html
    environment:
      - TZ=Europe/Moscow
      - MYSQL_ROOT_PASSWORD=dchsduV&3d3dnd8s7i7dfbY
      - MYSQL_DATABASE=CloudCrmWeb
      - MYSQL_USER=CloudCrmWeb
      - MYSQL_PASSWORD=CloudCrmWeb1secret23
    depends_on:
      - mysql

  mysql:
    platform: linux/x86_64
    image: mysql:8.0
    networks:
      - bridge
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - TZ=Europe/Moscow
      - MYSQL_ROOT_PASSWORD=dchsduV&3d3dnd8s7i7dfbY
      - MYSQL_DATABASE=CloudCrmWeb
      - MYSQL_USER=CloudCrmWeb
      - MYSQL_PASSWORD=CloudCrmWeb1secret23